### PR TITLE
Added watchlater, history and like functionalities and pages.

### PR DESCRIPTION
**Pull request by Hamza-777**
Please review and provide feedback, thank you.

### CODE REVIEW

**Review by md-amir-gauhar — APPROVED** [review]
Easy, readable code
Good work

**Review by ApurvaSawant11 — APPROVED** [review]
UI looks awesome 🥇  The code also looks clean

Just check if the authentication is working or not. I was not able to login.

**Comment by Hamza-777** [comment]
> UI looks awesome 🥇 The code also looks clean
> 
> Just check if the authentication is working or not. I was not able to login.

Will check @ApurvaSawant11 , thank you.

**Comment by Hamza-777** [comment]
> UI looks awesome 🥇 The code also looks clean
> 
> Just check if the authentication is working or not. I was not able to login.

Sorry, looks like I forgot to provide the environment variable in vercel.

**Pull request merged**
